server:
  port: 3122

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14.5:///test-core-database
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 16
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    table: "schema_version"

logging:
  level:
    server.access.log: WARN